### ISSUE TITLE
Bioconductor submission?

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/MsExperiment#24]
@lgatto , should we consider submitting this package to BioC (for the next release)?

**Comment by lgatto** [comment]
We can consider submitting it, sure. Could we may be first have a chat to see what to plans for further developments are? We don't need to have everything in before submission, of course.

**Comment by lgatto** [comment]
Submitted as [issue 2720](https://github.com/Bioconductor/Contributions/issues/2720)

**Comment by lgatto** [comment]
FYI @jorainer - we've received our review back. I haven't had time to look into it yet, but we could discuss at EuroBioc.

**Comment by lgatto** [comment]
1. Imports:
    - Importing selectively from the **methods** package is strongly discouraged. Note that you already import the whole **methods** package (`import(methods)`) so there's actually no need to selectively import things with `importFrom(methods,"slot<-")`, `importFrom(methods,as)`, `importMethodsFrom(methods,show)`, etc...
    - Same situation with **ProtGenerics**: you have `import(ProtGenerics)` so no need to `importFrom(ProtGenerics,spectra)`.
    - I would also strongly suggest that you import the whole **S4Vectors** and **IRanges**, just to avoid unnecessary maintenance complications in the future.

The global imports of **methods** and **ProtGenerics** were a mistake and have been removed. We don't mind selectively importing symbols from **S4Vectors** and **IRanges** - hope that's OK.

3. I suggest that you extend the `Annotated` class from **S4Vectors**. This will give you the `metadata()` getter and setter for free, and also will ensure that they behave consistently across all objects in the Bioconductor ecosystem.

Done.

```
> showClass("MsExperiment")
Class "MsExperiment" [package "MsExperiment"]

Slots:
                                                
Name:                            experimentFiles
Class:                         MsExperimentFiles
                                                
Name:                                    spectra
Class:                           Spectra_OR_Null
                                                
Name:                                      qdata
Class: QFeatures_OR_SummarizedExperiment_OR_Null
                                                
Name:                                  otherData
Class:                                      List
                                                
Name:                                 sampleData
Class:                                 DataFrame
                                                
Name:                            sampleDataLinks
Class:                                      List
                                                
Name:                                   metadata
Class:                                      list

Extends: "Annotated"
```

4. Given that the `assay` slot contains "quantification data" and that the slot is accessed via the `qdata()` getter and setter, why isn't the slot called `qdata`?

Indeed, we have changed as suggested:

```
> slotNames("MsExperiment")
[1] "experimentFiles" "spectra"         "qdata"           "otherData"      
[5] "sampleData"      "sampleDataLinks" "metadata"       
```

5. Can I suggest that you use the preferred `_OR_` convention for all your union classes? E.g. `MsExperimentFiles_OR_NULL` instead of `MsExperimentFilesOrNull`, and `QFeatures_OR_SummarizedExperiment_OR_NULL` instead of `QFeaturesOrSummarizedExperimentOrNull`, etc... BTW I'm not sure why you need the `MsExperimentFilesOrNull` class at all. Couldn't an empty (i.e. zero-length) `MsExperimentFiles` object be used when there are no files to store?

We are now following the `_OR_` convention and got rid of `MsExperimentFilesOrNull` as it wasn't needed.

6. For a MsExperiment object `mse` with 2 samples, I was expecting that `mse[ , 1:2]` would be a no-op but I get:
    ```
    > mse
    Object of class MsExperiment 
     Files: mzML_files, annotations 
     Spectra: MS1 (1862) 
     Experiment data: 2 sample(s)
     Sample data links:
      - experimentFiles.mzML_files: 2 sample(s) to 2 element(s).
      - experimentFiles.annotations: 2 sample(s) to 1 element(s).
      - spectra: 2 sample(s) to 1862 element(s).
    > identical(mse[,1:2], mse)
    [1] FALSE
    ```
    This makes me wonder if I really understand what subsetting does. 

See below for the list semantic. 

As for the non-identical `mse`and `mse[1:2]` objects, this is expected, as we need to copy filenames that are pointed to by more than one sample to guarantee the consistency between samples and their associated files. This has the side effect that you point out. This was mentioned/demonstratd in the vignette and now also in the man page.

7. I also wonder why enforce the use of the 2D syntax for subsetting (e.g. `mse[ , 1]`) instead of just using the simpler 1D syntax (e.g. `mse[1]`). This kind of suggests that MsExperiment objects are somehow 2D objects but they are not (`dim()` returns NULL). Have you considered giving these objects a 1D semantic? This would be achieved by: (a) giving them a `length()` (the number of samples), (b) allowing them to carry `names()` (the names/ids of the samples), and (c) allowing subsetting with `mse[i]` where `i` is either an integer vector (index), or a logical vector of the same length as `mse`, or a character vector of sample names/ids.

You are absolutely right, and we have changed the semantic accordingly:

```
> mse
Object of class MsExperiment 
 Files: mzML_files, annotations 
 Experiment data: 2 sample(s)
 Sample data links:
  - experimentFiles.mzML_files: 2 sample(s) to 2 element(s).
  - experimentFiles.annotations: 2 sample(s) to 1 element(s).
> length(mse)
[1] 2
> mse[1]
Object of class MsExperiment 
 Files: mzML_files, annotations 
 Experiment data: 1 sample(s)
 Sample data links:
  - experimentFiles.mzML_files: 1 sample(s) to 1 element(s).
  - experimentFiles.annotations: 1 sample(s) to 1 element(s).
 ```

9. Files created with `saveRDS()` are RDS files and thus should have the `.rds` extension. Looks like you're using `.rda` in the vignette (and maybe in other places).

This was a silly mistake - fixed now.

10. Some cosmetic:
    - Make sure to use `` `r Biocpkg("BiocManager")` `` instead of bare backticks for package names in the text of the vignette. 
    - Right now the `show()` method prints `Object of class MsExperiment` for an empty MsExperiment object. Would be nice if it could tell that the object is empty, like you did for QFeatures objects.

Both fixed.

```
> MsExperiment()
Empty object of class MsExperiment 
```

**Comment by lgatto** [comment]
Accepted!
